# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-02-11 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryOrder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='purchase_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseOrder.PurchaseOrder'),
        ),
    ]
