# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-02-11 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrder', '0001_initial'),
        ('DeliveryOrder', '0002_auto_20200211_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderitem',
            name='purchase_order_id',
            field=models.ForeignKey(default='PO1001', on_delete=django.db.models.deletion.CASCADE, to='PurchaseOrder.PurchaseOrder'),
            preserve_default=False,
        ),
    ]
